import React, { useContext, useEffect } from 'react'
import Layout from '../../../components/layout'
import Header from '../../../components/legendary/header'
import styles from "./Settings.module.scss"
import { observer } from 'mobx-react'
import Head from 'next/head'
import { Context } from '../../_app'
import SettingsNavigation from '../../../components/legendary/MiddleBlock/SettingsNavigation'

const Settings = () => {

    const {mobxStore} = useContext(Context);    

    useEffect(() => {
        console.log('work', localStorage.getItem('token'));
        if(localStorage.getItem('token')) {
        mobxStore.checkAuth()
        }
    }, [])

    return (
        <>
            <Head>
                <title>Настройки | GameCust</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1,  user-scalable=no" />\
                <link rel="stylesheet" type="text/css" charSet="UTF-8"
                    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
                <link rel="stylesheet" type="text/css"
                    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
                <link rel="shortcut ico" href="../public/favicon.svg" />
            </Head>
            <Header />
            <Layout>
                <div className={styles.leftColumn}>
                </div>
                <div className={styles.middleColumn}>
                    
                </div>
                <div className={styles.rightColumn}>
                    <SettingsNavigation />
                </div>
            </Layout>
        </>
    )
}

export default observer(Settings)