import Head from 'next/head'
import styles from './New.module.scss'
import React, {useContext, useEffect, useRef, useState} from "react";
import { observer } from 'mobx-react-lite'
import { Context } from '../_app';
import CreatePostRight from '../../components/legendary/RightBlock/CreatePostRight';
import Premium from '../../components/legendary/RightBlock/Premium';
import TopUsers from '../../components/legendary/RightBlock/TopUsers';
import NewsSliderSmall from '../../components/legendary/RightBlock/NewsSliderSmall';
import TopGroup from '../../components/legendary/RightBlock/TopGroup';
import Contacts from '../../components/legendary/RightBlock/Contacts';
import Layout from '../../components/layout';
import PostList from '../../components/legendary/MiddleBlock/PostList';
import Navigation from '../../components/legendary/MiddleBlock/Navigation';
import UserLeft from '../../components/legendary/LeftBlock/UserLeft';
import Header from '../../components/legendary/header';
import MainLayout from '../../components/layout/MainLayout';

const Subscriptions = ({ props } : any) => {
  
  const menuRef = useRef<HTMLUListElement>(null);
  console.log(process.env.NEXT_PUBLIC_API_URL);

  const [data, setData] = useState(props);
  
  const {mobxStore} = useContext(Context);
  
  useEffect(() => {
    if(localStorage.getItem('token')) {
      mobxStore.checkAuth()
    }
  }, [])

  const fetchData = async (page : any) => {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/post/getPosts/${page}`);
    const resultData = await res?.json();
    let resultProps = [] as any;
    let result = mobxStore?.user?.subscriptions?.forEach(subscription => {
        resultProps = resultData.filter((i : any) => i.userId === subscription)
    })
    setData(resultProps);
    console.log(resultProps);
    
    return resultProps
  }

  return (
    <>
      <Head>
        <title>GameCust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1,  user-scalable=no" />\
        <link rel="stylesheet" type="text/css" charSet="UTF-8"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
        <link rel="shortcut ico" href="../public/favicon.png" />
      </Head>
      <Header />
      <MainLayout>
        <PostList PostData={data} fetchData={fetchData} />
      </MainLayout>
    </>
  )
}


export async function getServerSideProps(context : any) {
  
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/post/getPosts/1`);
  
  return {
    props: {props : await res?.json()}, // will be passed to the page component as props
  }
}

export default observer(Subscriptions)
