import React, {useEffect, useRef, useState} from 'react';
import Head from "next/head";
import Header from "../../components/legendary/header";
import Layout from "../../components/layout";
import styles from './newArticle.module.scss'
import NewArticleBlock from "../../components/legendary/MiddleBlock/newArticleBlock";

const newArticle = () => {

  // const [showFixedMenu, setShowFixedMenu] = useState<boolean>(false);
  // const menuRef = useRef<HTMLUListElement>(null);
  //
  // useEffect(() => {
  //   if (typeof window !== 'undefined') {
  //     window.addEventListener('scroll', () => {
  //
  //       if (menuRef.current && menuRef.current.getBoundingClientRect().top <= 0) {
  //         setShowFixedMenu(true)
  //       } else {
  //         setShowFixedMenu(false)
  //       }
  //     })
  //   }
  // })

  return (
    <>
      <Head>
        <title>Опубликовать пост | GameCust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />\
        <link rel="stylesheet" type="text/css" charSet="UTF-8"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
        <link rel="icon" href="" />
      </Head>
      <Header />
      <Layout>
        {/*<div className={styles.leftColumn}>*/}
        {/*</div>*/}
        {/*<div className={styles.middleColumn}>*/}
        {/*  <NewArticleBlock />*/}
        {/*</div>*/}
        {/*<div className={styles.rightColumn}>*/}
        {/*</div>*/}
      </Layout>
    </>
  );
};

export default newArticle;
