import React, { useContext, useEffect } from 'react';
import Head from "next/head";
import Header from "../../../components/legendary/header";
import Layout from "../../../components/layout";
import styles from './Editor.module.scss'
import EditorBlock from "../../../components/legendary/MiddleBlock/editorBlock";
import { Context } from '../../_app';
import { useRouter } from 'next/router';

const Editor = () => {
  
  const {mobxStore, postCreateStore} = useContext(Context);
  const router = useRouter();
  const { postId } = router.query

  useEffect(() => {
    postCreateStore.updateArray([
      {
          type: 'h1',
          value: '',
          stared: false,
          id: 0,
      },
    ])
    const checkHandler = async () => {
      if(localStorage.getItem('token')) {
        await mobxStore.checkAuth()
      }
      
      if (!mobxStore.user.isActivated) {
        await router.push('/')
      }
    }
    checkHandler()
  }, [])
  console.log(postCreateStore);
  
  useEffect(() => {
    console.log(postId);
    postCreateStore.setPostId(postId ? postId[1] : '')
  }, [postId])

  return (
    <>
      <Head>
        <title>Опубликовать пост | GameCust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1,  user-scalable=no" />\
        <link rel="stylesheet" type="text/css" charSet="UTF-8"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
        <link rel="icon" href="" />
      </Head>
      <Header />
      <Layout>
        <div className={styles.leftColumn}>
        </div>
        <div className={styles.middleColumn}>
          <EditorBlock />
        </div>
        <div className={styles.rightColumn}>
        </div>
      </Layout>
    </>
  );
};

export default Editor;
