import React, {use, useContext, useEffect, useRef, useState} from 'react';
import Head from "next/head";
import Header from "../../../components/legendary/header";
import Layout from "../../../components/layout";
import styles from './Profile.module.scss'
import CreatePostRight from "../../../components/legendary/RightBlock/CreatePostRight";
import Premium from "../../../components/legendary/RightBlock/Premium";
import TopUsers from "../../../components/legendary/RightBlock/TopUsers";
import NewsSliderSmall from "../../../components/legendary/RightBlock/NewsSliderSmall";
import TopGroup from "../../../components/legendary/RightBlock/TopGroup";
import Contacts from "../../../components/legendary/RightBlock/Contacts";
import BackWallpaper from "../../../components/legendary/BackWallpaper";
import LoginRight from "../../../components/legendary/RightBlock/LoginRight";
import ProfileBlock from "../../../components/legendary/MiddleBlock/Profile";
import PostList from "../../../components/legendary/MiddleBlock/PostList";
import { observer } from 'mobx-react-lite';
import { Context } from '../../_app';
import { useRouter } from 'next/router';
import UserService from '../../../utils/user/UserService';

const Profile = () => {
 
  const router = useRouter();
  const {profile} = router.query as any;
  console.log(profile);
  
  const [showFixedMenu, setShowFixedMenu] = useState<boolean>(false);
  const menuRef = useRef<HTMLUListElement>(null);

  const {mobxStore} = useContext(Context);

  const [user, setUser] = useState({})

  async function fetchUser(id: any) {
    try {
      console.log(id);
      const response = await UserService.fetchUser(id)
      if(response.data === null) {
        router.push('/')
      }
      setUser(response.data)
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    if(profile?.length && profile?.length >= 1) {
      fetchUser(profile[0])
    }
  }, [profile])

  useEffect(() => {
    console.log('work', localStorage.getItem('token'));
  
    if(localStorage.getItem('token')) {
      mobxStore.checkAuth()
    }
    
  }, [])

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.addEventListener('scroll', () => {

        if (menuRef.current && menuRef.current.getBoundingClientRect().top <= -140) {
          setShowFixedMenu(true)
        } else {
          setShowFixedMenu(false)
        }
      })
    }
  })

  return (
    <>
      <Head>
        <title>Пост | GameCust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1,  user-scalable=no" />\
        <link rel="stylesheet" type="text/css" charSet="UTF-8"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
        <link rel="icon" href="" />
      </Head>
      <Header />
      <BackWallpaper />
      <Layout>
        <div className={styles.middleColumn}>
          <ProfileBlock data={user} />
          <PostList />
        </div>
        <div className={styles.rightColumn}>
          <LoginRight />
          <CreatePostRight />
          <Premium />
          <TopUsers />
          <ul className={styles.fixedBar} ref={menuRef}></ul>
          <NewsSliderSmall />
          <TopGroup />
          <Contacts />
          <div style={{opacity: showFixedMenu ? 1 : 0, zIndex: showFixedMenu ? 1 : -2}} className={styles.rightColumnFixed}>
            <LoginRight />
            <CreatePostRight />
            <Premium />
            <TopUsers />
            <NewsSliderSmall />
            <TopGroup />
            <Contacts />
          </div>
        </div>
      </Layout>
    </>
  );
};

export default observer(Profile);
