import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Layout from "../components/layout";
import Header from "../components/legendary/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>GameCust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <Layout>
        <Header />
      </Layout>
    </>
  )
}
