import React, {useEffect, useRef, useState} from 'react';
import Head from "next/head";
import Header from "../../../components/legendary/header";
import Layout from "../../../components/layout";
import styles from './Post.module.scss'
import CreatePostRight from "../../../components/legendary/RightBlock/CreatePostRight";
import Premium from "../../../components/legendary/RightBlock/Premium";
import TopUsers from "../../../components/legendary/RightBlock/TopUsers";
import NewsSliderSmall from "../../../components/legendary/RightBlock/NewsSliderSmall";
import TopGroup from "../../../components/legendary/RightBlock/TopGroup";
import Contacts from "../../../components/legendary/RightBlock/Contacts";
import Post from "../../../components/legendary/common/Post";
import LoginRight from "../../../components/legendary/RightBlock/LoginRight";
import { useRouter } from 'next/router';
import CreatePostService from '../../../utils/createPost/CreatePostService';

const MyComponent = () => {
 
  const router = useRouter();
  const {post} = router.query as any;

  const [data, setData] = useState<any>({});

  async function fetchPost(id: any) {
    try {
      console.log(id);  
      const response = await CreatePostService.getPost(id)
      if(response.data === null) {
        router.push('/')
      }
      setData(response.data)
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    if(post?.length && post?.length >= 1) {
      fetchPost(post[0])
    }
  }, [post])

  return (
    <>
      <Head>
        <title>Пост | GameCust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1,  user-scalable=no" />\
        <link rel="stylesheet" type="text/css" charSet="UTF-8"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
        <link rel="stylesheet" type="text/css"
              href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
        <link rel="icon" href="" />
      </Head>
      <Header />
      <Layout>
        <div className={styles.middleColumn}>
          <Post data={data} />
        </div>
        <div className={styles.rightColumn}>
          <LoginRight />
          <CreatePostRight />
          <Premium />
          <TopUsers />
          <ul className={styles.fixedBar}></ul>
          <NewsSliderSmall />
          <TopGroup />
          <Contacts />
        </div>
      </Layout>
    </>
  );
};

export default MyComponent;