import Head from 'next/head'
import React from 'react'
import Header from '../../components/legendary/header'
import Layout from '../../components/layout'
import PremiumSettingsBlock from '../../components/legendary/MiddleBlock/PremiumSettingsBlock'

const GameCustPlus = () => {
  return (
    <>
        <Head>
            <title>GameCust Plus - Подписка | GameCust</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1,  user-scalable=no" />\
            <link rel="stylesheet" type="text/css" charSet="UTF-8"
                href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"/>
            <link rel="stylesheet" type="text/css"
                href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"/>
            <link rel="icon" href="" />
        </Head>
        <Header />
        <Layout>
            <PremiumSettingsBlock />
        </Layout>
    </>
  )
}

export default GameCustPlus